/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salinometer;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
//import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
//import java.time.ZoneOffset;
import java.time.ZonedDateTime;
//import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.TimeZone;
import java.util.prefs.Preferences;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


/**
 *
 * @author pena
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    private Preferences prefs;
    private dataSyncingSingleton syncData = dataSyncingSingleton.getInstance();
    private SerialPort port;
    private CommPortIdentifier portId = null;
    private SalinometerSerialRead srr=null;
    private File pWD;
    private String OS = System.getProperty("os.name").toLowerCase();
    private JProgressBar progressBar;

    public mainView() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("resources/saltbottle.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDialog1 = new javax.swing.JDialog();
        mainJPanel = new javax.swing.JPanel();
        autosalConnectJButtonWithIcon = new javax.swing.JButton();
        mainJScrollPane = new javax.swing.JScrollPane();
        mainJTable = new javax.swing.JTable();
        salinometerConnectJButton = new javax.swing.JButton();
        mainMenuJToolBar = new javax.swing.JToolBar();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        fileNewJButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        fileOpenJButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        printPageJButton = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        runDetailsJButton = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        calibrateJButton = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        csvExportJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        functionSwitchStatusJTextField = new javax.swing.JTextField();
        timeJTextField = new javax.swing.JTextField();
        dateJTextField = new javax.swing.JTextField();
        dataPathJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salinometerJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        NewJMenuItem = new javax.swing.JMenuItem();
        OpenJMenuItem = new javax.swing.JMenuItem();
        closeJMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        printJMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        runDetailsJMenuItem = new javax.swing.JMenuItem();
        calibrateJMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exitJMenuItem = new javax.swing.JMenuItem();
        loggingJMenu = new javax.swing.JMenu();
        communicationsLogJMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        enterBottleLabelJMenuItem = new javax.swing.JMenuItem();
        enterCommentsJMenuItem = new javax.swing.JMenuItem();
        settingsJMenu = new javax.swing.JMenu();
        generalJMenuItem = new javax.swing.JMenuItem();
        communicationsJMenuItem = new javax.swing.JMenuItem();
        columnsJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        technicalHelpJMenuItem = new javax.swing.JMenuItem();
        licenseAgreementJMenuItem = new javax.swing.JMenuItem();
        aboutJMenuItem = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AOML Salinometer Data Logger");

        mainJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainJPanel.setMaximumSize(new java.awt.Dimension(80, 112));
        mainJPanel.setMinimumSize(new java.awt.Dimension(25, 25));

        autosalConnectJButtonWithIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salinometerConnectionNotConnected.png"))); // NOI18N
        autosalConnectJButtonWithIcon.setBorder(null);
        autosalConnectJButtonWithIcon.setBorderPainted(false);
        autosalConnectJButtonWithIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autosalConnectJButtonWithIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(autosalConnectJButtonWithIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(autosalConnectJButtonWithIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainJScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainJScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        mainJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sample ID", "Bottle Label", "Date/Time", "Bath Temp", "Uncorr Ratio", "Uncorrected Ratio SD", "Correction", "Adj Ratio", "Calc Salinity", "Calc Salinity SD", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mainJTable.getTableHeader().setReorderingAllowed(false);
        mainJScrollPane.setViewportView(mainJTable);
        if (mainJTable.getColumnModel().getColumnCount() > 0) {
            mainJTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            mainJTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            mainJTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            mainJTable.getColumnModel().getColumn(3).setPreferredWidth(120);
            mainJTable.getColumnModel().getColumn(4).setPreferredWidth(120);
            mainJTable.getColumnModel().getColumn(5).setPreferredWidth(160);
            mainJTable.getColumnModel().getColumn(6).setPreferredWidth(120);
            mainJTable.getColumnModel().getColumn(7).setPreferredWidth(120);
            mainJTable.getColumnModel().getColumn(8).setPreferredWidth(150);
            mainJTable.getColumnModel().getColumn(9).setPreferredWidth(160);
            mainJTable.getColumnModel().getColumn(10).setPreferredWidth(150);
        }

        salinometerConnectJButton.setText("Connect");
        salinometerConnectJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salinometerConnectJButtonActionPerformed(evt);
            }
        });

        mainMenuJToolBar.setBorder(null);
        mainMenuJToolBar.setFloatable(false);
        mainMenuJToolBar.setRollover(true);
        mainMenuJToolBar.add(jSeparator10);

        fileNewJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filenew.png"))); // NOI18N
        fileNewJButton.setToolTipText("New Run");
        fileNewJButton.setBorder(null);
        fileNewJButton.setFocusable(false);
        fileNewJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileNewJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileNewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewJButtonActionPerformed(evt);
            }
        });
        mainMenuJToolBar.add(fileNewJButton);
        mainMenuJToolBar.add(jSeparator5);

        fileOpenJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileopen.png"))); // NOI18N
        fileOpenJButton.setBorder(null);
        fileOpenJButton.setFocusable(false);
        fileOpenJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileOpenJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainMenuJToolBar.add(fileOpenJButton);
        mainMenuJToolBar.add(jSeparator6);

        printPageJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fileprint.png"))); // NOI18N
        printPageJButton.setBorder(null);
        printPageJButton.setFocusable(false);
        printPageJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printPageJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainMenuJToolBar.add(printPageJButton);
        mainMenuJToolBar.add(jSeparator7);

        runDetailsJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/properties.png"))); // NOI18N
        runDetailsJButton.setBorder(null);
        runDetailsJButton.setFocusable(false);
        runDetailsJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        runDetailsJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainMenuJToolBar.add(runDetailsJButton);
        mainMenuJToolBar.add(jSeparator8);

        calibrateJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flaskNobg.png"))); // NOI18N
        calibrateJButton.setBorder(null);
        calibrateJButton.setFocusable(false);
        calibrateJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calibrateJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainMenuJToolBar.add(calibrateJButton);
        mainMenuJToolBar.add(jSeparator9);

        csvExportJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/text-csv.png"))); // NOI18N
        csvExportJButton.setBorder(null);
        csvExportJButton.setFocusable(false);
        csvExportJButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        csvExportJButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainMenuJToolBar.add(csvExportJButton);

        jLabel1.setText("Function Switch:");

        functionSwitchStatusJTextField.setEditable(false);
        functionSwitchStatusJTextField.setText("Not Connected");
        functionSwitchStatusJTextField.setBorder(null);
        functionSwitchStatusJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functionSwitchStatusJTextFieldActionPerformed(evt);
            }
        });

        timeJTextField.setEditable(false);
        timeJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timeJTextField.setText("13:55:00");
        timeJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        timeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeJTextFieldActionPerformed(evt);
            }
        });

        dateJTextField.setEditable(false);
        dateJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateJTextField.setText("05/17/2017");
        dateJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dataPathJTextField.setEditable(false);
        dataPathJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dataPathJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPathJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Data Path:");
        jLabel2.setBorder(null);

        salinometerJMenuBar.setPreferredSize(new java.awt.Dimension(185, 17));

        fileJMenu.setText("File");

        NewJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewJMenuItem.setText("New");
        NewJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(NewJMenuItem);

        OpenJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenJMenuItem.setText("Open...");
        fileJMenu.add(OpenJMenuItem);

        closeJMenuItem.setText("Close");
        closeJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(closeJMenuItem);
        fileJMenu.add(jSeparator1);

        printJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        printJMenuItem.setText("Print");
        fileJMenu.add(printJMenuItem);
        fileJMenu.add(jSeparator2);

        runDetailsJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        runDetailsJMenuItem.setText("Run Details");
        fileJMenu.add(runDetailsJMenuItem);

        calibrateJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        calibrateJMenuItem.setText("Calibrate");
        fileJMenu.add(calibrateJMenuItem);
        fileJMenu.add(jSeparator3);

        exitJMenuItem.setText("Exit");
        exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(exitJMenuItem);

        salinometerJMenuBar.add(fileJMenu);

        loggingJMenu.setText("Logging");

        communicationsLogJMenuItem.setText("Communications Log");
        loggingJMenu.add(communicationsLogJMenuItem);
        loggingJMenu.add(jSeparator4);

        enterBottleLabelJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        enterBottleLabelJMenuItem.setText("Enter Bottle Lable");
        loggingJMenu.add(enterBottleLabelJMenuItem);

        enterCommentsJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        enterCommentsJMenuItem.setText("Enter Comments");
        loggingJMenu.add(enterCommentsJMenuItem);

        salinometerJMenuBar.add(loggingJMenu);

        settingsJMenu.setText("Settings");

        generalJMenuItem.setText("General");
        generalJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalJMenuItemActionPerformed(evt);
            }
        });
        settingsJMenu.add(generalJMenuItem);

        communicationsJMenuItem.setText("Communications...");
        communicationsJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communicationsJMenuItemActionPerformed(evt);
            }
        });
        settingsJMenu.add(communicationsJMenuItem);

        columnsJMenuItem.setText("Columns...");
        columnsJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnsJMenuItemActionPerformed(evt);
            }
        });
        settingsJMenu.add(columnsJMenuItem);

        salinometerJMenuBar.add(settingsJMenu);

        helpJMenu.setText("Help");

        technicalHelpJMenuItem.setText("Technical Help");
        helpJMenu.add(technicalHelpJMenuItem);

        licenseAgreementJMenuItem.setText("License Agreement");
        helpJMenu.add(licenseAgreementJMenuItem);

        aboutJMenuItem.setText("About...");
        helpJMenu.add(aboutJMenuItem);

        salinometerJMenuBar.add(helpJMenu);

        setJMenuBar(salinometerJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(functionSwitchStatusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(salinometerConnectJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mainMenuJToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataPathJTextField)
                                .addGap(24, 24, 24)
                                .addComponent(dateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(mainJScrollPane))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainMenuJToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(functionSwitchStatusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salinometerConnectJButton)))
                    .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataPathJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dataPathJTextField, dateJTextField, jLabel2, timeJTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {functionSwitchStatusJTextField, jLabel1, salinometerConnectJButton});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewJMenuItemActionPerformed
        // TODO add your handling code here:
        newRun();

    }//GEN-LAST:event_NewJMenuItemActionPerformed

    private void generalJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalJMenuItemActionPerformed
        SettingsOptions so = new SettingsOptions();
        so.pack();
        so.setLocationRelativeTo(this);
        so.setModal(true);
        so.setVisible(true);


    }//GEN-LAST:event_generalJMenuItemActionPerformed

    private void communicationsJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communicationsJMenuItemActionPerformed

        CommunicationsSettings cs = new CommunicationsSettings();
        cs.pack();
        cs.setLocationRelativeTo(this);
        cs.setModal(true);
        cs.setVisible(true);


    }//GEN-LAST:event_communicationsJMenuItemActionPerformed

    private void columnsJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnsJMenuItemActionPerformed
        // TODO add your handling code here:        
        SelectColumns sc = new SelectColumns();
        sc.pack();
        sc.setLocationRelativeTo(this);
        sc.setModal(true);
        sc.setVisible(true);


    }//GEN-LAST:event_columnsJMenuItemActionPerformed

    private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitJMenuItemActionPerformed

    private void timeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeJTextFieldActionPerformed

    private void fileNewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewJButtonActionPerformed
        // TODO add your handling code here:
        newRun();

  
    }//GEN-LAST:event_fileNewJButtonActionPerformed

    private void autosalConnectJButtonWithIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autosalConnectJButtonWithIconActionPerformed
        // TODO add your handling code here:

        
        
        if (syncData.isSerialPortOpen()) {
            disconnectSerialPort();

        } else {

            connectSerialPort();
           
        }
    }//GEN-LAST:event_autosalConnectJButtonWithIconActionPerformed

    private void salinometerConnectJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salinometerConnectJButtonActionPerformed
        // TODO add your handling code here:
        if (syncData.isSerialPortOpen()) {
            disconnectSerialPort();
            
        } else {

            connectSerialPort();
       
        }

    }//GEN-LAST:event_salinometerConnectJButtonActionPerformed

    private void closeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJMenuItemActionPerformed
        // TODO add your handling code here:
        this.disconnectSerialPort();
        syncData.setRunCreated(false);
    }//GEN-LAST:event_closeJMenuItemActionPerformed

    private void dataPathJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPathJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPathJTextFieldActionPerformed

    private void functionSwitchStatusJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_functionSwitchStatusJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_functionSwitchStatusJTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //mainView mv = new mainView();
                //mv.init();
                // mv.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NewJMenuItem;
    private javax.swing.JMenuItem OpenJMenuItem;
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JButton autosalConnectJButtonWithIcon;
    private javax.swing.JButton calibrateJButton;
    private javax.swing.JMenuItem calibrateJMenuItem;
    private javax.swing.JMenuItem closeJMenuItem;
    private javax.swing.JMenuItem columnsJMenuItem;
    private javax.swing.JMenuItem communicationsJMenuItem;
    private javax.swing.JMenuItem communicationsLogJMenuItem;
    private javax.swing.JButton csvExportJButton;
    private javax.swing.JTextField dataPathJTextField;
    private javax.swing.JTextField dateJTextField;
    private javax.swing.JMenuItem enterBottleLabelJMenuItem;
    private javax.swing.JMenuItem enterCommentsJMenuItem;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JButton fileNewJButton;
    private javax.swing.JButton fileOpenJButton;
    private javax.swing.JTextField functionSwitchStatusJTextField;
    private javax.swing.JMenuItem generalJMenuItem;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JMenuItem licenseAgreementJMenuItem;
    private javax.swing.JMenu loggingJMenu;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JScrollPane mainJScrollPane;
    private javax.swing.JTable mainJTable;
    private javax.swing.JToolBar mainMenuJToolBar;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JButton printPageJButton;
    private javax.swing.JButton runDetailsJButton;
    private javax.swing.JMenuItem runDetailsJMenuItem;
    private javax.swing.JButton salinometerConnectJButton;
    private javax.swing.JMenuBar salinometerJMenuBar;
    private javax.swing.JMenu settingsJMenu;
    private javax.swing.JMenuItem technicalHelpJMenuItem;
    private javax.swing.JTextField timeJTextField;
    // End of variables declaration//GEN-END:variables

    //declare variables here
    private TableColumnModel tcm;
    private TableColumn bottleLabel;

    private void newRun() {
        
        boolean cancel = false;
        boolean retry = false;
        SalinometerNotDetected snd;
        connectSerialPort();

        if (!syncData.isSalinometerConnected()) {
            do {
                snd = new SalinometerNotDetected(this, true);
                snd.pack();
                snd.setModal(true);
                snd.setLocationRelativeTo(this);
                snd.setVisible(true);

                cancel = snd.getCancel();
                retry = snd.getRetry();

                if (retry) {
                    connectSerialPort();
                    retry = false;
                }//end if

            } while (!cancel && !syncData.isSalinometerConnected());

        }

        if (syncData.isSalinometerConnected()) {

            SampleRun sr = new SampleRun();
            sr.pack();
            sr.setModal(true);
            sr.setLocationRelativeTo(this);
            sr.setVisible(true);
            enableItems();

        }//end if
        else{
        disconnectSerialPort();
        
        }//end else
    }//end newRun;

    
    private void connectSerialPort() {
        try {
            if (srr == null) {
                portId = CommPortIdentifier.getPortIdentifier(prefs.get("serialPortName", "COM1"));
                port = (SerialPort) portId.open("Salinometer", 10000);
                port.setSerialPortParams(9600, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
                port.setFlowControlMode(SerialPort.FLOWCONTROL_NONE);
                
                srr = new SalinometerSerialRead(port);
                salinometerConnectJButton.setText("Disconnect");
                syncData.setSerialPortOpen(true);
                //enableItems();
                Thread.sleep(1000);
            }
        }//end try
        catch (Exception e) {
            e.printStackTrace();
            salinometerConnectJButton.setText("Connect");
            srr=null;
            disableItems();

        }//end catch

    }//end connectSerialPort
    
    
    private void disconnectSerialPort(){ 
        if (srr != null) {
            srr.close();
            srr = null;}//end f
            syncData.setSalinometerConnected(false);
            syncData.setSerialPortOpen(false);
            salinometerConnectJButton.setText("Connect");
            disableItems();
        
    
    
    
    }//end disconnectSerialPort
    

    private void disableItems() {
        calibrateJButton.setEnabled(false);
        calibrateJMenuItem.setEnabled(false);
        closeJMenuItem.setEnabled(false);
        printJMenuItem.setEnabled(false);
        printPageJButton.setEnabled(false);
        runDetailsJButton.setEnabled(false);
        runDetailsJMenuItem.setEnabled(false);
        communicationsLogJMenuItem.setEnabled(false);
        enterBottleLabelJMenuItem.setEnabled(false);
        enterCommentsJMenuItem.setEnabled(false);
        csvExportJButton.setEnabled(false);
        communicationsJMenuItem.setEnabled(true);
        generalJMenuItem.setEnabled(true);
        mainJTable.getParent().setEnabled(false);
        mainJTable.getParent().setVisible(false);
        mainJTable.setEnabled(false);
        mainJTable.setVisible(false);
    }//end method
    
 
    private void enableItems() {
        calibrateJButton.setEnabled(true);
        calibrateJMenuItem.setEnabled(true);
        closeJMenuItem.setEnabled(true);
        printJMenuItem.setEnabled(true);
        printPageJButton.setEnabled(true);
        runDetailsJButton.setEnabled(true);
        runDetailsJMenuItem.setEnabled(true);
        communicationsLogJMenuItem.setEnabled(true);
        enterBottleLabelJMenuItem.setEnabled(true);
        enterCommentsJMenuItem.setEnabled(true);
        csvExportJButton.setEnabled(true);
        communicationsJMenuItem.setEnabled(false);
        generalJMenuItem.setEnabled(false);
        mainJTable.getParent().setEnabled(true);
        mainJTable.getParent().setVisible(true);       
        mainJTable.setEnabled(true);
        mainJTable.setVisible(true);

    }//end method   
    

    void init() {
        prefs = Preferences.userNodeForPackage(getClass());
        String defaultPWD=System.getProperty("user.home") + File.separatorChar + "data" + File.separatorChar + "salinometer";
        
                if (OS.indexOf("win") >= 0) {
            defaultPWD = System.getProperty("user.home")+File.separatorChar  + "Documents"+File.separatorChar + "data" + File.separatorChar + "salinometer";
        }//end if
        
        


        try{
        pWD = new File(defaultPWD);
        pWD.mkdirs();
        }
        catch(Exception e){
        
        pWD.mkdirs();
        pWD = new File(System.getProperty(defaultPWD));
        }
        this.dataPathJTextField.setText(pWD.getPath());

        syncData.setSalinometerConnected(false);
        tcm = mainJTable.getColumnModel();
        bottleLabel = tcm.getColumn(1);
        disableItems();
        try {
            MrUpdate updater = new MrUpdate(dateJTextField, timeJTextField, autosalConnectJButtonWithIcon,functionSwitchStatusJTextField);

        }//end try
        catch (Exception e) {
            e.printStackTrace();
        }//end catch

        //tcm.removeColumn(bottleLabel);
        





    }//end init()

    public class MrUpdate implements Runnable {

        Thread thisThread;
        JTextField dateUTCJTextField;
        JTextField timeUTCJTextField;
        JTextField functionSwitchStatus;
        JButton connectionIconJButton;
        Icon notConnected;
        Icon connected1;
        Icon connected2;
        Icon connected3;
        Icon connected4;
        Icon connected5;
        Icon connected6;
        Icon connected7;
        Icon connected8;
        String dateUTC;
        String timeUTC;
        String functionSwitchStatusMsg;
        int iconCounter;
        DateFormat dateFormat;
        DateFormat timeFormat;

        public MrUpdate(JTextField theDate, JTextField theTime, JButton icon ,JTextField status) {

            dateUTCJTextField = theDate;
            timeUTCJTextField = theTime;
            connectionIconJButton = icon;
            functionSwitchStatus = status;
            connected1 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected1.png"));
            connected2 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected2.png"));
            connected3 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected3.png"));
            connected4 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected4.png"));
            connected5 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected5.png"));
            connected6 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected6.png"));
            connected7 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected7.png"));
            connected8 = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnected8.png"));
            notConnected = new javax.swing.ImageIcon(getClass().getResource("/salinometerConnectionNotConnected.png"));
            iconCounter = 0;
            dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            timeFormat = new SimpleDateFormat("HH:mm:ss");
            dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
            timeFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
            thisThread = new Thread(this, "Mr Update");
            thisThread.start();
            

        }//end constrcutor

        @Override
        public void run() {
            ZonedDateTime utc;
            boolean connectedToSalinometer = false;
            long currentSystemTime = System.currentTimeMillis();
            long previousSystemTime = System.currentTimeMillis();
            long previousConnectionIconTime = System.currentTimeMillis();

            while (true) {
                currentSystemTime = System.currentTimeMillis();
                connectedToSalinometer = syncData.isSalinometerConnected();
                try {
                    Thread.sleep(50);

                    //updating date and time here
                    if (currentSystemTime - previousSystemTime >= 250) {
//                        utc = ZonedDateTime.now(ZoneOffset.UTC);
//                        timeUTC = utc.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
//                        dateUTC = utc.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                        timeUTC = timeFormat.format(new Date());
                        dateUTC = dateFormat.format(new Date());
                        dateUTCJTextField.setText(dateUTC);
                        timeUTCJTextField.setText(timeUTC);
                        functionSwitchStatusMsg=syncData.getFunctionStatus();
                        if(!syncData.isSalinometerConnected()){
                            functionSwitchStatusMsg="No Connection";
                        }//end if
                        functionSwitchStatus.setText(functionSwitchStatusMsg);

                        previousSystemTime = System.currentTimeMillis();

                    }//end if

                    //updating connection icon
                    if (connectedToSalinometer && (currentSystemTime - previousConnectionIconTime > 500)) {

                        switch (iconCounter) {
                            case 0:
                                connectionIconJButton.setIcon(connected1);
                                iconCounter = 1;
                                break;

                            case 1:
                                connectionIconJButton.setIcon(connected2);
                                iconCounter = 2;
                                break;
                            case 2:
                                connectionIconJButton.setIcon(connected3);
                                iconCounter = 3;
                                break;
                            case 3:
                                connectionIconJButton.setIcon(connected4);
                                iconCounter = 4;
                                break;
                            case 4:
                                connectionIconJButton.setIcon(connected5);
                                iconCounter = 5;
                                break;
                            case 5:
                                connectionIconJButton.setIcon(connected6);
                                iconCounter = 6;
                                break;
                            case 6:
                                connectionIconJButton.setIcon(connected7);
                                iconCounter = 7;
                                break;
                            case 7:
                                connectionIconJButton.setIcon(connected8);
                                iconCounter = 8;
                                break;

                            case 8:
                                connectionIconJButton.setIcon(connected7);
                                iconCounter = 9;
                                break;
                            case 9:
                                connectionIconJButton.setIcon(connected6);
                                iconCounter = 10;
                                break;
                            case 10:
                                connectionIconJButton.setIcon(connected5);
                                iconCounter = 11;
                                break;
                            case 11:
                                connectionIconJButton.setIcon(connected4);
                                iconCounter = 12;
                                break;
                            case 12:
                                connectionIconJButton.setIcon(connected3);
                                iconCounter = 13;
                                break;
                            case 13:
                                connectionIconJButton.setIcon(connected2);
                                iconCounter = 0;
                                break;

                        }//end switch
                        
                        

                        previousConnectionIconTime = System.currentTimeMillis();

                    }//end if

                    if (!connectedToSalinometer) {
                        connectionIconJButton.setIcon(notConnected);
                        iconCounter = 0;

                    }//end else

                }//end try
                catch (Exception e) {
                    e.printStackTrace();
                }//end catch
            }
        }//end while

        void updateDate(JTextField date) {
            dateUTCJTextField = date;

        }//end method        

        void updateTime(JTextField time) {
            timeUTCJTextField = time;

        }//end method

        void updateConnectionIcon(JButton connectionButton) {
            connectionIconJButton = connectionButton;

        }//end method

    }//end mrUpdate 

}
