/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salinometer;

/**
 *
 * @author user
 */
public class ProgressBarJDialog extends javax.swing.JDialog /*implements Runnable*/ {

    /**
     * Creates new form ProgressBarJDialog
     */
    //Thread thisThread;
    int maxVal;
    int minVal;
    int currentVal;

    public ProgressBarJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(parent);
        //jProgressBar.setMinimum(1);
        //jProgressBar.setMaximum(10);
        //thisThread = new Thread(this, "Progress Bar");
        //thisThread.start();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readingProgressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        cancelJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("progressBarDialog"); // NOI18N
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextArea.setRows(5);
        jTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea);

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(readingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(readingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JProgressBar readingProgressBar;
    // End of variables declaration//GEN-END:variables

 /*   @Override
    public void run() {
dataSyncingSingleton dataSync = dataSyncingSingleton.getInstance();

        try {
            while (currentVal <= maxVal) {
//                readingProgressBar.setCurrentValue(currentVal);
                readingProgressBar.repaint();
                //jProgressBar.setVisible(true);
               System.out.println("currentVal="+currentVal);
                
                //thisThread.sleep(500);
           

            }//end for
           
        } catch (Exception e) {
            e.printStackTrace();
        }

    }*/
    
    public void setMinimumValue(int val) {
        minVal=val;
        readingProgressBar.setMinimum(minVal);

    }

    public void setMaximumValue(int val) {
        maxVal=val;
        readingProgressBar.setMaximum(maxVal);
    }

    public void setCurrentValue(int val) {
        currentVal = val;
        readingProgressBar.setValue(currentVal);
        //System.out.println("currentVal="+currentVal);
        //readingProgressBar.repaint();
        
       // readingProgressBar.setCurrentValue(currentVal);
    }

    public void startProgressBar() {
        //hisThread = new Thread(this, "Progress Bar");
        //thisThread.start();

    }
    
    public void setMessage(String msg){
    jTextArea.setText(msg);
    }
    
    public void setDialogTitle(String msg){
        setTitle(msg);
    
    }
    
    

}//end class
